apiVersion: apps/v1
kind: Deployment
metadata:
  name: httprequest
  labels:
    app: httprequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httprequest
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: httprequest
    spec:
      containers:
      - name: httprequest
        #replace <foobar> with your container registry. Example: contosodemo.azurecr.io
        image: sharedglobalservices.azurecr.io/dongkun-canary-test
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
