apiVersion: v1
kind: Service
metadata:
  name: httprequest
  labels:
    app: httprequest
spec:
  selector:
    app: httprequest
  ports:
  - name: metrics
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  type: ClusterIP
